<a href="https://colab.research.google.com/github/AhmedGDeeb/DataTalksClub/blob/main/machine-learning-zoomcamp/cohorts/2026/homework/homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Set up the environment

In [1]:
!pip install pandas matplotlib numpy seaborn

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# Q1. Pandas version

In [59]:
import pandas as pd
import numpy as np

In [4]:
pd.__version__

'2.2.3'

# Getting the data

In [6]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-20 08:42:18--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.04s

2026-09-20 08:42:18 (14.5 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]

In [7]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB

- correct data types, some null values

In [9]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

- possible ranges of values

In [10]:
df.sample(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
6560,2023,Asia,Gasoline,Front-wheel drive,2,1960,5,223.0,3980,17.7,34.3
8399,2011,Asia,Hybrid,Front-wheel drive,2,2360,6,254.0,4270,15.8,35.3
4831,2004,USA,Diesel,All-wheel drive,3,2410,7,280.0,4890,19.7,27.3
8400,2012,Asia,Gasoline,Front-wheel drive,3,2110,5,225.0,4300,19.9,33.1
2511,2010,USA,Gasoline,Rear-wheel drive,4,2090,5,231.0,4360,20.2,29.2

## Q2. Records count

How many records are in the dataset?

In [11]:
len(df)

10000

# Q3. Fuel types

How many fuel types are presented in the dataset?

In [29]:
# fuel types
df['fuel_type'].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

In [25]:
# count of fuel types
len(df['fuel_type'].unique())

3

# Q4. Missing values

How many columns in the dataset have missing values?

In [28]:
# how many missing values in each column
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [22]:
# sum of columns that have missing values
sum(df.isnull().sum() > 0)

2

# Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [30]:
# what is values in origin first
df['origin'].unique()

array(['Europe', 'Asia', 'USA'], dtype=object)

In [34]:
# get all the rows in Asia only
asia_df = df[df['origin'] == "Asia"]
asia_df.sample(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2692,1984,Asia,Gasoline,Front-wheel drive,4,2470,7,NaN,4400,19.1,28.5
4148,2022,Asia,Gasoline,Front-wheel drive,5,2170,6,242.0,4390,21.1,32.2
3755,1988,Asia,Gasoline,Rear-wheel drive,4,2480,7,274.0,4520,20.3,29.5
8759,1993,Asia,Gasoline,Rear-wheel drive,2,2380,6,244.0,4390,19.0,24.8
6210,1978,Asia,Diesel,All-wheel drive,4,2370,6,NaN,4520,18.3,33.1

In [37]:
# sort by efficiency
asia_df['fuel_efficiency_mpg'].max()

41.2

# Q6. Median value of horsepower

In [43]:
# 1. Find the median value of the horsepower column in the dataset.
meidan_before = df['horsepower'].median()
meidan_before

254.0

In [39]:
# 2. Next, calculate the most frequent value of the same horsepower column.
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [40]:
# 3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
horsepower = df['horsepower'].fillna(df['horsepower'].mode())

In [41]:
# 4. Now, calculate the median value of horsepower once again.
meidan_after = horsepower.median()
meidan_after

254.0

In [44]:
# Has it changed?
if meidan_after > meidan_before:
    print("Yes, it increased")
elif meidan_after < meidan_before:
    print("Yes, it decreased")
else:
    print("No")

No

# Q7. Sum of weights

In [82]:
# 1. Select all the cars from Asia
asia_df = df[df['origin'] == "Asia"]

In [83]:
# 2. Select only columns vehicle_weight and model_year
asia_df = asia_df[['vehicle_weight', 'model_year']]

In [84]:
# 3. Select the first 7 values
df_sample = asia_df.head(7)

In [85]:
# 4. Get the underlying NumPy array. Let's call it X.
X = df_sample.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [86]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [87]:
# 6. Invert XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [88]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [89]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv @ X.T @ y

In [90]:
# 9. What's the sum of all the elements of the result?
sum(w)

np.float64(0.36919696904925486)

This is essentially the **normal equation** for least-squares regression:
$$w = (X^T X)^{-1} X^T y$$